---
title: "Volleyball game encoder"
format:
  dashboard:
    expandable: false
server: shiny
fontsize: "14px"
---

```{r}
#| context: setup
#| include: false
library(shiny)
library(shinyjs)
library(DT)
library(fontawesome)
useShinyjs(rmd = TRUE)
source("R/utils_players.R")
```

# Game

```{r}
#| layout: "[[1,1,1,1], [1,1,1,1], [1,1,1,1], [1,1,1,1], [1,1,1]]"
# Must be called from the UI side to use `shinyjs` functions from an Rmd file
useShinyjs(rmd = TRUE)

# Input to indicate the name of the "home" team
textInput(
  "home_team",
  value = "LVBC", # TO_REMOVE
  label = tags$p(icon("house"), "Home team")
)
# Input to indicate the name of the "away" (or visiting) team
textInput(
  "away_team",
  value = "LUC", # TO_REMOVE
  label = tags$p(icon("suitcase-rolling"), "Away team")
)
br()

br()

# Input to let the user indicate which of the two teams is her/his
selectInput(
  "my_team",
  label = "Your team?",
  choices = ""
)
# Input to indicate which team started to serve
selectInput(
  "serving_set_1",
  label = "Which team won the service after the toss?",
  choices = ""
)
br()

br()
# Input to indicate the place the game took place
textInput(
  "game_location",
  label = tags$p(fa("location-dot", fill = "#020618"), "Location"),
  value = "here" # TO_REMOVE
)
# Input to indicate the date the game took place
dateInput(
  "game_date",
  label = tags$p(fa("calendar", fill = "#020618"), "Date"),
  format = "dd-mm-yyyy",
  value = "2026-02-01" # TO_REMOVE
)
br()

br()
# Input to indicate the season during which the game was played
selectInput(
  "season",
  label = tags$p(fa("location-dot", fill = "#020618"), "Season"),
  # choices = c(
  #  "", vapply(2025:2000, \(x) paste0(x + 1, " - ", x), FUN.VALUE = "character")
  # ),
  choices = c(
    vapply(2025:2000, \(x) paste0(x + 1, " - ", x), FUN.VALUE = "character")
  ) # TO_REMOVE
)
# Input to indicate the division/league of the two teams
textInput(
  "division",
  label = tags$p(icon("layer-group"), "Division"),
  value = "1", # TO_REMOVE
)
br()

br()
# Action button to lock the data entered on the "Game" page. This is the only
# way to allow the user continuing.
actionButton(
  "lock_details",
  label = "Lock game details",
  icon = icon("lock")
)
br()
```

# Player

## {.sidebar width=200px}
::: {style="font-size: 120%;"}
```{r}
# Side panel button to import players (NOT IMPLEMENTED YET)
fileInput("import_players_file", "Choose a file")
actionButton(
  "import_players",
  label = "Import players",
  icon = icon("file-arrow-down")
)
```
:::

## Row

### Column {width=50%}

```{r}
#| layout: "[[1], [1,1,1], [1], [1,1,1]]"
# This page allows to enter the players of the two teams registered in the game
# sheet. For each player, the number must be entered, as well as names and
# roles (having names and roles mandatory is questioned). A player can be added
# to the list by hitting "+ Add player".
#
# After a player has been added, it can be removed by selecting the
# corresponding line in the players list, then hitting the "x Remove player"
# button (several players can be removed at the same time).
#
# When the list of a team is complete, the user must hit "Validate players".
# The "Set 1" tab becomes available when the players of the two teams have been
# validated.
#
# A list of players can be validated when 6 players at least are entered
# (excluding libero).

h5(
  textOutput("home_team_players_tab"),
  style = "text-align: center;font-weight: bold;"
)

# Input to indicate the name of a home player to add
textInput(
  "new_player_name_home",
  label = tags$p(icon("address-card"), "Player name")
)
# Input to indicate the role of a home player to add
selectInput(
  "new_player_role_home",
  label = tags$p(icon("gear"), "Player role"),
  choices = c(
    "",
    "Setter",
    "Outside hitter",
    "Middle blocker",
    "Opposite",
    "Libero"
  ),
  width = "280px"
)
# Input to indicate the number of a home player to add (between 1 and 99)
numericInput(
  "new_player_num_home",
  label = tags$p(icon("shirt"), "Player #"),
  value = NULL,
  min = 1,
  max = 99
)

br()

# Action button to add a home player (name, role and number must be valid for
# the button to be active).
actionButton(
  "add_player_home",
  label = tags$p(icon("plus"), "Add player"),
  disabled = TRUE
)
# Action button to validate all home players already added (the button is active
# only if at least 6 numbers are listed, excluding libero).
actionButton(
  "validate_player_home",
  label = tags$p(icon("circle-check"), "Validate players"),
  disabled = TRUE,
  style = "background-color: #93c47d"
)
# Action button to remove all the home players in the `home_players_tbl` that
# are active (active means that the player(s) corresponding row(s) are
# selected).
actionButton(
  "remove_player_home",
  label = tags$p(icon("circle-xmark"), "Remove player"),
  disabled = TRUE,
  style = "background-color: #f77b7b"
)
```

### Column {width=50%, height=65%}

```{r}
# Table listing the players entered for the home team
dataTableOutput("home_players_tbl")
```

## Row

```{r}
#| layout: "[[1], [1,1,1], [1], [1,1,1]]"
# Same as above but here were are dealing with the UI to add away players

h5(
  textOutput("away_team_players_tab"),
  style = "text-align: center;font-weight: bold;"
)

# Input to indicate the name of an away player to add
textInput(
  "new_player_name_away",
  label = tags$p(icon("address-card"), "Player name")
)
# Input to indicate the role of an away player to add
selectInput(
  "new_player_role_away",
  label = tags$p(icon("gear"), "Player role"),
  choices = c(
    "",
    "Setter",
    "Outside hitter",
    "Middle blocker",
    "Opposite",
    "Libero"
  ),
  width = "280px"
)
# Input to indicate the number of an away player to add (between 1 and 99)
numericInput(
  "new_player_num_away",
  label = tags$p(icon("shirt"), "Player #"),
  value = NULL,
  min = 1,
  max = 99
)

br()

# Action button to add an away player (name, role and number must be valid for
# the button to be active).
actionButton(
  "add_player_away",
  label = tags$p(icon("plus"), "Add player"),
  disabled = TRUE
)
# Action button to validate all away players already added (the button is
# active only if at least 6 numbers are listed, excluding libero).
actionButton(
  "validate_player_away",
  label = tags$p(icon("circle-check"), "Validate players"),
  disabled = TRUE,
  style = "background-color: #93c47d"
)
# Action button to remove all the away players in the `home_players_tbl` that
# are active (active means that the player(s) corresponding row(s) are
# selected).
actionButton(
  "remove_player_away",
  label = tags$p(icon("circle-xmark"), "Remove player"),
  disabled = TRUE,
  style = "background-color: #f77b7b"
)
```

### Column {width=50%, height=65%}

```{r}
# Table listing the players entered for the home team
dataTableOutput("away_players_tbl")
```

<!--
The UI for a set page is a page composed of two tabsets ("home" and "away").
Each tabset has two parts. The left part with the interface to enter base
rotation, substitutions, and time-outs. The right part contains the interface
to add the score at the end of each rotation (i.e the end of each team series
of service).

For simplicity, the code chunks for the left part UI is sourced from .qmd files,
one for each set and each team (see code under "R/positions_chunks/"). The code
chunks for for right part UI is sourced from .qmd files, one for each set and
each team (see code under "R/set_rotations_chunks/").
-->

# Set 1

## Row {.tabset}

### Home

#### Row

```{r}
#| height: 60px
#| padding: 0px
h4(textOutput("home_team_out_1"), style = "text-align: center;")
```

##### Column

{{< include R/position_chunks/set_1_home_positions.qmd >}}
{{< include R/score_rotations_chunks/set_1_home_rotations.qmd >}}

### Away

```{r}
#| height: 60px
#| padding: 0px
h4(textOutput("away_team_out_1"), style="text-align: center;")
```

#### Column

{{< include R/position_chunks/set_1_away_positions.qmd >}}
{{< include R/score_rotations_chunks/set_1_away_rotations.qmd >}}

## Row

```{r}
#| height: 40px
#| padding: 0px
# Action button to go to the next set. The button is active only when the score
# indicates the score is over (the team with the highest score has at least 25
# and a difference of 2 points). When button is hit, the following is checked:
#   - completeness of rotations
#   - if a score is entered when a substitution is also entered
#   - the format of substitution scores (XX:XX)
#   - the format of time-outs (XX:XX)

actionButton(
  "next_to_set_2",
  label = "Next set",
  icon = icon("arrow-right"),
  style = "height: 40px;width: 100px, align-self: center;"
)
```

# Set 2

## Row {.tabset}

### Home

#### Row

```{r}
#| height: 60px
#| padding: 0px
h4(textOutput("home_team_out_2"), style="text-align: center;")
```

##### Column

{{< include R/position_chunks/set_2_home_positions.qmd >}}
{{< include R/score_rotations_chunks/set_2_home_rotations.qmd >}}

### Away

```{r}
#| height: 60px
#| padding: 0px
h4(textOutput("away_team_out_2"), style="text-align: center;")
```

##### Column

{{< include R/position_chunks/set_2_away_positions.qmd >}}
{{< include R/score_rotations_chunks/set_2_away_rotations.qmd >}}

## Row

```{r}
#| height: 40px
#| padding: 0px
actionButton(
  "next_to_set_3",
  label = "Next set",
  icon = icon("arrow-right"),
  style = "height: 40px;width: 100px, align-self: center;"
)
```

# Set 3

## Row {.tabset}

### Home

#### Row

```{r}
#| height: 60px
#| padding: 0px
h4(textOutput("home_team_out_3"), style="text-align: center;")
```

##### Column

{{< include R/position_chunks/set_3_home_positions.qmd >}}
{{< include R/score_rotations_chunks/set_3_home_rotations.qmd >}}

### Away

```{r}
#| height: 60px
#| padding: 0px
h4(textOutput("away_team_out_3"), style="text-align: center;")
```

##### Column

{{< include R/position_chunks/set_3_away_positions.qmd >}}
{{< include R/score_rotations_chunks/set_3_away_rotations.qmd >}}

## Row

```{r}
#| height: 40px
#| padding: 0px
actionButton(
  "next_to_set_4",
  label = "Next set",
  icon = icon("arrow-right"),
  style = "height: 40px;width: 100px, align-self: center;"
)
```

# Set 4

## Row {.tabset}

### Home

#### Row

```{r}
#| height: 60px
#| padding: 0px
h4(textOutput("home_team_out_4"), style="text-align: center;")
```

##### Column

{{< include R/position_chunks/set_4_home_positions.qmd >}}
{{< include R/score_rotations_chunks/set_4_home_rotations.qmd >}}

### Away

```{r}
#| height: 60px
#| padding: 0px
h4(textOutput("away_team_out_4"), style="text-align: center;")
```

##### Column

{{< include R/position_chunks/set_4_away_positions.qmd >}}
{{< include R/score_rotations_chunks/set_4_away_rotations.qmd >}}

## Row

```{r}
#| height: 40px
#| padding: 0px
actionButton(
  "next_to_set_5",
  label = "Next set",
  icon = icon("arrow-right"),
  style = "height: 40px;width: 100px, align-self: center;"
)
```

# Set 5

## Row {.tabset}

### Home

#### Row

```{r}
#| height: 60px
#| padding: 0px
h4(textOutput("home_team_out_5"), style="text-align: center;")
```

##### Column

{{< include R/position_chunks/set_5_home_positions.qmd >}}
{{< include R/score_rotations_chunks/set_5_home_rotations.qmd >}}

### Away

```{r}
#| height: 60px
#| padding: 0px
h4(textOutput("away_team_out_5"), style="text-align: center;")
```

##### Column

{{< include R/position_chunks/set_5_away_positions.qmd >}}
{{< include R/score_rotations_chunks/set_5_away_rotations.qmd >}}

## Row

```{r}
#| height: 40px
#| padding: 0px
actionButton(
  "next_to_summary",
  label = "Next set",
  icon = icon("arrow-right"),
  style = "height: 40px;width: 100px, align-self: center;"
)
```

# Summary

```{r}
#| layout-align: center
#| height: "350px"
#| layout: "[[1,1,1,3,3,1,1,1], [5,2,5], [11, 1]]"
br()
bslib::value_box(
  # The name of home team
  title = div(
    icon("repeat"),
    style = paste0(
      "text-align: center;",
      "font-weight: bold;",
      "font-size: 20px;",
      "border-bottom: 1px solid 'white';",
      "padding-bottom: 0.5rem"
    )
  ),
  fill = FALSE,
  value = div(style = "font-size: 30px;"),
  tagList(
    div(
      textOutput("home_sub_set_1"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("home_sub_set_2"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("home_sub_set_3"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("home_sub_set_4"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("home_sub_set_5"),
      style = paste0("text-align: center;font-size:14px")
    )
  )
)

bslib::value_box(
  # The name of home team
  title = div(
    icon("stopwatch"),
    style = paste0(
      "text-align: center;",
      "font-weight: bold;",
      "font-size: 20px;",
      "border-bottom: 1px solid 'white';",
      "padding-bottom: 0.5rem"
    )
  ),
  fill = FALSE,
  value = div(style = "font-size: 30px;"),
  tagList(
    div(
      textOutput("home_to_set_1"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("home_to_set_2"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("home_to_set_3"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("home_to_set_4"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("home_to_set_5"),
      style = paste0("text-align: center;font-size:14px")
    )
  )
)

bslib::value_box(
  # The name of home team
  title = h2(
    textOutput("home_team_out"),
    style = paste0(
      "text-align: center;",
      "font-weight: bold;",
      "font-size: 20px;",
      "border-bottom: 1px solid;",
      "padding-bottom: 0.5rem"
    )
  ),
  fill = FALSE,
  # Number of sets won by the home team
  value = div(
    textOutput("home_sets"),
    style = "text-align: center;font-size: 30px;"
  ),
  theme = bslib::value_box_theme(bg = "#517699", fg = "#e6f2fd"),
  class = "border",
  # Points won by the home team in each set
  tagList(
    div(
      textOutput("home_score_set_1"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("home_score_set_2"),
      style = paste0("text-align: center;")
    ),
    div(
      textOutput("home_score_set_3"),
      style = paste0("text-align: center;")
    ),
    div(
      textOutput("home_score_set_4"),
      style = paste0("text-align: center;")
    ),
    div(
      textOutput("home_score_set_5"),
      style = paste0("text-align: center;")
    )
  )
)


bslib::value_box(
  # The name of away team
  title = h2(
    textOutput("away_team_out"),
    style = paste0(
      "text-align: center;",
      "font-weight: bold;",
      "font-size: 20px;",
      "border-bottom: 1px solid;",
      "padding-bottom: 0.5rem"
    )
  ),
  fill = FALSE,
  # Number of sets won by the away team
  value = div(
    textOutput("away_sets"),
    style = "text-align: center;font-size: 30px;"
  ),
  theme = bslib::value_box_theme(bg = "#517699", fg = "#e6f2fd"),
  class = "border",
  # Points won by the home team in each set
  tagList(
    div(
      textOutput("away_score_set_1"),
      style = paste0(
        "text-align: center;",
        textOutput("away_score_set_1_style")
      )
    ),
    div(
      textOutput("away_score_set_2"),
      style = paste0(
        "text-align: center;",
        textOutput("away_score_set_2_style")
      )
    ),
    div(
      textOutput("away_score_set_3"),
      style = paste0(
        "text-align: center;",
        textOutput("away_score_set_3_style")
      )
    ),
    div(
      textOutput("away_score_set_4"),
      style = paste0(
        "text-align: center;",
        textOutput("away_score_set_4_style")
      )
    ),
    div(
      textOutput("away_score_set_5"),
      style = paste0(
        "text-align: center;",
        textOutput("away_score_set_5_style")
      )
    )
  )
)

bslib::value_box(
  # The name of home team
  title = div(
    icon("stopwatch"),
    style = paste0(
      "text-align: center;",
      "font-weight: bold;",
      "font-size: 20px;",
      "border-bottom: 1px solid 'white';",
      "padding-bottom: 0.5rem"
    )
  ),
  fill = FALSE,
  value = div(style = "font-size: 30px;"),
  tagList(
    div(
      textOutput("away_to_set_1"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("away_to_set_2"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("away_to_set_3"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("away_to_set_4"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("away_to_set_5"),
      style = paste0("text-align: center;font-size:14px")
    )
  )
)

bslib::value_box(
  # The name of home team
  title = div(
    icon("repeat"),
    style = paste0(
      "text-align: center;",
      "font-weight: bold;",
      "font-size: 20px;",
      "border-bottom: 1px solid 'white';",
      "padding-bottom: 0.5rem"
    )
  ),
  fill = FALSE,
  value = div(style = "font-size: 30px;"),
  tagList(
    div(
      textOutput("away_sub_set_1"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("away_sub_set_2"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("away_sub_set_3"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("away_sub_set_4"),
      style = paste0("text-align: center;font-size:14px")
    ),
    div(
      textOutput("away_sub_set_5"),
      style = paste0("text-align: center;font-size:14px")
    )
  )
)
br()
br()
downloadButton(
  "export_game_data",
  label = "Export game data",
  icon = icon("file-export")
)
br()
br()
actionButton(
  "close_app",
  label = "Close app",
  icon = icon("circle-stop"),
  style = "background-color: #f77b7b"
)
```


```{r}
#| context: server

#==============================================================================|
#                           ---- Reactive values ----
#==============================================================================|

# Reactive value defining whether the game details input should be locked or not
are_details_locked <- reactiveVal(FALSE)

# Define whether home and away players have been validated by the users allowing
# then to make the "Set 1" tab active.
are_players_validated <- reactiveValues(home = FALSE, away = FALSE)

# The data frames with the list of home and away players
players <- reactiveValues(
  home_team = data.frame(
    Number = character(),
    Name = character(),
    Role = character()
  ),
  away_team = data.frame(
    # Number = character(),
    # Name = character(),
    # Role = character()
    # TO_REMOVE
    Number = c("12", "51", "15", "5", "4", "38", "1"),
    Name = c(letters[1:7]),
    Role = c("Setter", rep("Outside hitter", 2), rep("Middle blocker", 2), "Opposite", "Libero")
  )
)

# Initiate reactive values with the players available (i.e. not assigned to any
# position) for the two teams and each set.
available_players <- reactiveValues(
  set_1 = list(home = NULL, away = NULL),
  set_2 = list(home = NULL, away = NULL),
  set_3 = list(home = NULL, away = NULL),
  set_4 = list(home = NULL, away = NULL),
  set_5 = list(home = NULL, away = NULL)
)

# Initiate a reactive value with the number of player available in the list of
# players to import.
in_import <- reactiveValues(
  players = NULL,
  selected = NULL
)
import_player_dt_tbl <- reactiveVal(NULL)
# players_in_import_sel <- reactiveValues(NULL)
# players_in_import_df <- reactiveVal(NULL)
# n_players_in_import <- reactiveVal(0)

# Reactive values with:
#   - the number of set completed (based on scores only)
#   - whether game is over (based on the scores only)
#   - if the data are ready to export
# The values are updated any time there is an interaction with the app.
n_sets <- reactiveVal(0)
is_game_over <- reactiveVal(FALSE)
data_ready_for_export <- reactiveVal(FALSE)


#==============================================================================|
#                          ---- "Game" tab events ----
#==============================================================================|

# When any of the two teams' name is updated, it is updated accordingly anywhere
# the names are used.
observeEvent(list(input$home_team, input$away_team), {
  # Update the "my_team" selector
  updateSelectInput(
    inputId = "my_team",
    choices = c("", input$home_team %||% "", input$away_team %||% "")
  )
  # Update the output with the name of the teams for each set tab
  lapply(
    1:6,
    \(x) {
      output[[paste0("home_team_out_", x)]] <- renderText({
        input$home_team %||% ""
      })
      output[[paste0("away_team_out_", x)]] <- renderText({
        input$away_team %||% ""
      })
    }
  )
  output$home_team_players_tab <- renderText({ input$home_team %||% "" })
  output$away_team_players_tab <- renderText({ input$away_team %||% "" })
  # Update the selector allowing to indicate which team started to serve in the
  # game.
  updateSelectInput(
    inputId = "serving_set_1",
    choices = c("", input$home_team %||% "", input$away_team %||% "")
  )
  # Update the selector allowing to indicate which team started to serve in the
  # fifth set. The selector is displayed only when a fifth set is played.
  updateSelectInput(
    inputId = "serving_set_5",
    choices = c("", input$home_team %||% "", input$away_team %||% "")
  )
})

# Observer running checks on the "Game" page any time there is an interaction
# with the app. All the input/selector on the page are checked to see if none
# is null or empty. If they are all ok, the reactive value `any_empty_game_page`
# is set to TRUE to allow enabling the locking button and then "Set 1" tab.
observe({
  # ID of the elements to check
  elem_to_check <- list(
    "home_team", "away_team", "my_team", "serving_set_1", "season", "division"
  )
  # Check all elements in 
  any_empty <- any(unlist(lapply(
    elem_to_check,
    \(x) any(is.null(input[[x]]), !nzchar(input[[x]]))
  )))
  
  # Enable the "Lock details" button based on whether there is any element that
  # is empty on the corresponding page or not.
  if (!any_empty && !are_details_locked()) {
    shinyjs::enable("lock_details")
  } else if (any_empty && !are_details_locked()) {
    shinyjs::disable("lock_details")
  }
})

# When the details in the first tab are locked, the "player" tab appears in the
# top navbar.
observe({
  if (are_details_locked()) {
    shinyjs::showElement("tab-player", anim = TRUE, animType = "fade")
  } else {
    shinyjs::hideElement("tab-player")
  }
})

# When clicking the lock/unlock game details button, update the state of the
# game details inputs.
observeEvent(input$lock_details, {
  shinyjs::toggleState("home_team")
  shinyjs::toggleState("away_team")
  shinyjs::toggleState("my_team")
  shinyjs::toggleState("serving_set_1")
  shinyjs::toggleState("game_location")
  shinyjs::toggleState("game_date")
  shinyjs::toggleState("season")
  shinyjs::toggleState("division")
  
  if (are_details_locked()) {
    # When the details are locked we switch to unlocked state when the button is
    # clicked.
    updateActionButton(
      inputId = "lock_details",
      label = "Lock game details",
      icon = icon("lock")
    )
    # Details are unlocked
    are_details_locked(FALSE)
  } else {
    # When the details are unlocked we switch to locked state when the button is
    # clicked.
    updateActionButton(
      inputId = "lock_details",
      label = "Unlock game details",
      icon = icon("lock-open")
    )
    # Details are locked
    are_details_locked(TRUE)
  }
})

#==============================================================================|
#                        ---- "Players" tab events ----
#==============================================================================|

## Import players -------------------------------------------------------------

observeEvent(input$import_players, {
  # Read the list of potential players to import from the provided file
  json_players <- read_json(
    input$import_players_file$datapath,
    simplifyVector = TRUE
  )
  # Turn the players to import from JSON to data table and assign it to the
  # reactive.
  in_import$players <- fromJSON(json_players)
  
  # Combine the check buttons and the data frame with players to import and
  # assign to the reactive with the DT table to render in the import model.
  # import_player_dt_tbl(cbind(check_buttons, in_import$players))
  
  # Render the DT table with the players to import... with some settings
  output$import_player_dt_out <- renderDataTable(
    datatable(
      in_import$players,
      # We do not need the "check" buttons column to be named, but
      # zero-character are not allowed so we name it with an unbreakable space.
      rownames = FALSE,
      escape = FALSE,
      # We allow the user to edit the cells except for the first column with the
      # check buttons.
      editable = "cell",
      # Additional options...
      options = list(
        # We do not want paging or searching
        paging = FALSE,
        searching = FALSE
      ),
      selection = "multiple"
    )
  )
  
  # Once everything has been set up, we show the modal with the table with the
  # players to import.
  showModal(
    modalDialog(
      title = "Import players from previous games",
      # Some instructions on how to use the import tab
      tagList(
        HTML(
          "<ul><li><b>Editing players</b>: you can double-click on any ",
          "field to edit the number, name, and role of the players in the ",
          "table.</li>",
          "<li><b>Selecting players</b>: click on a row to select a player ",
          "(you can select more than one player at a time).</li>",
          "<li><b>Importing players</b>: click on <code>Import</code> at the ",
          "bottom to import all the selected players.</li></lu>"
        )
      ),
      footer = tagList(
        modalButton("Cancel"),
        actionButton(
          "import_players_confirm",
          "Import",
          style = "background-color: #93c47d"
        )
      ),
      easyClose = FALSE,
      size = "l",
      dataTableOutput("import_player_dt_out")
    )
  )
})

observeEvent(input$import_player_dt_out_cell_edit, {
  # Get the edits from the table
  edit_dat <- input$import_player_dt_out_cell_edit
  # Table has 0-indexing for columns so we need to add one to its index
  edit_dat[, "col"] <- edit_dat[, "col"] + 1
  # Update the reactive with the data underlying the DT table with players to
  # import to take into consideration the changes.
  in_import$players <- editData(in_import$players, edit_dat)
})

observeEvent(input$import_players_confirm, {
  # Get the index of the rows selected when the "Import" button is clicked
  players_in_import_sel_tmp <- input$import_player_dt_out_rows_selected
  # Subset the reactive with the data underlying the DT table with the players
  # to import with only those selected.
  players_to_import <- in_import$players[players_in_import_sel_tmp, ]
  # Combine the players already added to the game with the ones currently
  # selected to import.
  players_home_tmp <- rbind(players$home_team, players_to_import)
  # From the players already added and those to import, count the number of the
  # players to identify duplicates.
  dup_players_count <- table(players_home_tmp$Number)
  # Extract the duplicated players (if any)
  dup_players <- names(dup_players_count)[dup_players_count > 1]

  # Check if the players to import have liberos and if adding them would lead
  # to having more than 2.
  if (sum(players_home_tmp$Role == "Libero") > 2) {
    showNotification(
      "There are already two liberos engaged for the game.",
      type = "error"
    )
    # Check if the players to import would lead to go above 12 field players
    # (excluding liberos).
  } else if (sum(players_home_tmp$Role != "Libero") > 12) {
    showNotification(
      "There are already 12 non-libero players engaged for the game.",
      type = "error"
    )
    # Check if importing players would lead to have duplicated numbers
  } else if (length(dup_players) > 0) {
    # Display a notification indicating which numbers already exist in the
    # players already added to the game.
    dup_players_string <- switch(
      as.character(length(dup_players)),
      "1" = paste0(
        "There is already a player engaged with the number ",
        dup_players,
        "."
      ),
      paste0(
        "There are already players engaged with the following numbers: ",
        paste0(dup_players, collapse = ", "),
        "."
      )
    )
    showNotification(dup_players_string, type = "error")
  } else {
    # If the players to import do not violate the rules above, we then update
    # the DT table with the players in the game with the one to import.
    players$home_team <- players_home_tmp
    if (sum(players_in_import_sel_tmp) > 0) {
      # Once the new player is added to the table, the new table is rendered
      output$home_players_tbl <- renderDataTable({
        tbl <- players$home_team
        tbl[["Number"]] <- as.character(tbl[["Number"]])
        datatable(
          tbl,
          # Since the number of players should be up to 14, we disable paging.
          # We also do not need the searching option
          options = list(paging = FALSE, searching = FALSE),
          # Allow selection of multiple rows (useful to remove more than one
          # player at once from the table.)
          selection = "multiple"
        )
      })
    }
    removeModal()
  }
})

## Adding new home team player -------------------------------------------------

# Define whether the "add_new_player_home" button should be enabled (only when a
# number, a name, and a role is provided).
observe({
  is_new_home_num_ok <- all(
    # Cannot be NULL
    !is.null(input$new_player_num_home),
    # Cannot be one already used number
    !(input$new_player_num_home %in% as.numeric(players$home_team[["Number"]])),
    # Cannot be outside the 1 to 99 range
    input$new_player_num_home %in% 1:99
  )
  is_new_home_name_ok <- all(
    # Cannot be NULL
    !is.null(input$new_player_name_home),
    # Cannot be empty
    input$new_player_name_home != ""
  )
  is_new_home_role_ok <- all(
    # Cannot be NULL
    !is.null(input$new_player_role_home),
    # Cannot be empty
    input$new_player_role_home != ""
  )
  # Enable or disable the button accordingly
  if (!all(is_new_home_num_ok, is_new_home_name_ok, is_new_home_role_ok)) {
    shinyjs::disable("add_player_home")
  } else {
    shinyjs::enable("add_player_home")
  }
})

# When all conditions are met, enable the "validate home players" button for the
# home team.
observe({
  # Number of players in the home team's list
  n_players <- nrow(players$home_team)
  # Number of libero in the home team's list
  n_liberos <- sum(players$home_team[["Role"]] == "Libero")
  # Is the number of players in the list (excluding liberos) is at least 6?
  is_n_enough <- (n_players - n_liberos) >= 6
  # Is the number of libero not higher than 2?
  is_libero_not_too_many <- n_liberos <= 2
  # Is the number of players in the list (including liberos) is not above 14?
  is_n_not_too_many <- n_players <= 14
  # Enable or disable the button accordingly
  if (all(is_n_enough, is_n_not_too_many)) {
    shinyjs::enable("validate_player_home")
  } else {
    shinyjs::disable("validate_player_home")
  }
})

# When the home players are validated, then all the buttons in the corresponding
# card and the table with the list of players are disabled.
observeEvent(input$validate_player_home, {
  shinyjs::disable("new_player_name_home")
  shinyjs::disable("new_player_role_home")
  shinyjs::disable("new_player_num_home")
  shinyjs::disable("remove_player_home")
  shinyjs::disable("home_players_tbl")

  output$home_players_tbl <- renderDataTable({
    datatable(
      players$home_team,
      options = list(paging = FALSE, searching = FALSE),
      # Deactivate selection in the table
      selection = "none"
    )
  })
  # Update the "home" element in the reactive value `are_players_validated`
  are_players_validated$home <- TRUE
  shinyjs::disable("validate_player_home")
})

observeEvent(list(are_players_validated$home, are_players_validated$away), {
  if (all(are_players_validated$home, are_players_validated$away)) {
    shinyjs::disable("import_players_file")
    shinyjs::disable("import_players")
  }
})


## Adding new home team player -------------------------------------------------

# Define whether the "add_new_player_away" button should be enabled (only when a
# number, a name, and a role is provided).
observe({
  is_new_away_num_ok <- all(
    # Cannot be NULL
    !is.null(input$new_player_num_away),
    # Cannot be one already used number
    !(input$new_player_num_away %in% as.numeric(players$away_team[["Number"]])),
    # Cannot be outside the 1 to 99 range
    input$new_player_num_away %in% 1:99
  )
  is_new_away_name_ok <- all(
    # Cannot be NULL
    !is.null(input$new_player_name_away),
    # Cannot be empty
    input$new_player_name_away != ""
  )
  is_new_away_role_ok <- all(
    # Cannot be NULL
    !is.null(input$new_player_role_away),
    # Cannot be empty
    input$new_player_role_away != ""
  )
  # Enable or disable the button accordingly
  if (!all(is_new_away_num_ok, is_new_away_name_ok, is_new_away_role_ok)) {
    shinyjs::disable("add_player_away")
  } else {
    shinyjs::enable("add_player_away")
  }
})

# When all conditions are met, enable the "validate home players" button for the
# away team.
observe({
  # Number of players in the away team's list
  n_players <- nrow(players$away_team)
  # Number of libero in the away team's list
  n_liberos <- sum(players$away_team[["Role"]] == "Libero")
  # Is the number of players in the list (excluding liberos) is at least 6?
  is_n_enough <- (n_players - n_liberos) >= 6
  # Is the number of libero not higher than 2?
  is_libero_not_too_many <- n_liberos <= 2
  # Is the number of players in the list (including liberos) is not above 14?
  is_n_not_too_many <- n_players <= 14
  # Enable or disable the button accordingly
  if (all(is_n_enough, is_n_not_too_many)) {
    shinyjs::enable("validate_player_away")
  } else {
    shinyjs::disable("validate_player_away")
  }
})

# When the away players are validated, then all the buttons in the corresponding
# card and the table with the list of players are disabled.
observeEvent(input$validate_player_away, {
  shinyjs::disable("new_player_name_away")
  shinyjs::disable("new_player_role_away")
  shinyjs::disable("new_player_num_away")
  shinyjs::disable("remove_player_away")
  shinyjs::disable("away_players_tbl")

  output$away_players_tbl <- renderDataTable({
    datatable(
      players$away_team,
      options = list(paging = FALSE, searching = FALSE),
      # Deactivate selection in the table
      selection = "none"
    )
  })
  # Update the "away" element in the reactive value `are_players_validated`
  are_players_validated$away <- TRUE
  shinyjs::disable("validate_player_away")
})

## Home team players table -----------------------------------------------------

# When adding a new player for the home team, the list of player is updated in
# the player table and the input fields are emptied.
observeEvent(input$add_player_home, {
  # Create a data frame with the info of the player added and bind to the
  # already existing table of players.
  players$home_team <- rbind(
    players$home_team,
    data.frame(
      Number = as.character(input$new_player_num_home),
      Name = input$new_player_name_home,
      Role = input$new_player_role_home
    )
  )
  # Once the new player is added to the table, the new table is rendered
  output$home_players_tbl <- renderDataTable({
    tbl <- players$home_team
    tbl[["Number"]] <- as.character(tbl[["Number"]])
    datatable(
      tbl,
      # Since the number of players should be up to 14, we disable paging. We
      # also do not need the searching option
      options = list(paging = FALSE, searching = FALSE),
      # Allow selection of multiple rows (useful to remove more than one player
      # at once from the table.)
      selection = "multiple"
    )
  })
  # Empty the three player's input by updating their value with an empty string
  updateNumericInput(inputId = "new_player_num_home", value = "")
  updateSelectInput(inputId = "new_player_role_home", selected = "")
  updateTextInput(inputId = "new_player_name_home", value = "")
})

# When no player is listed in the home team, the table listing them is not shown
observe({
  if (is.null(input$home_players_tbl_rows_selected)) {
    shinyjs::disable("remove_player_home")
  } else {
    shinyjs::enable("remove_player_home")
  }
})

# Take care to remove from the home players table the one(s) selected when the
# remove button is hit.
observeEvent(input$remove_player_home, {
  # List the players in the table
  tbl <- players$home_team
  # Identify the players selected in the table when the remove button is hit
  to_rmv <- as.numeric(input$home_players_tbl_rows_selected)
  # Remove the selected player(s) from the table
  players$home_team <- tbl[-to_rmv, ]

  # If all players are removed (table has no row), a NULL table is rendered
  if (nrow(players$home_team) == 0) {
    output$home_players_tbl <- renderDataTable({
      NULL
    })
    # If at least one player remains in the table, it is rendered again
  } else {
    output$home_players_tbl <- renderDataTable({
      datatable(
        players$home_team,
        # Since the number of players should be up to 14, we disable paging. We
        # also do not need the searching option
        options = list(paging = FALSE, searching = FALSE),
        # Allow selection of multiple rows (useful to remove more than one player
        # at once from the table.)
        selection = "multiple"
      )
    })
  }
})

## Away team players table -----------------------------------------------------

# When adding a new player for the away team, the list of player is updated,
# the player table, and the input fields are emptied.
observeEvent(input$add_player_away, {
  # Create a data frame with the info of the player added and bind to the
  # already existing table of players.
  players$away_team <- rbind(
    players$away_team,
    data.frame(
      Number = as.character(input$new_player_num_away),
      Name = input$new_player_name_away,
      Role = "a"
    )
  )
  # Once the new player is added to the table, the new table is rendered
  output$away_players_tbl <- renderDataTable({
    tbl <- players$away_team
    tbl[["Number"]] <- as.character(tbl[["Number"]])
    datatable(
      tbl,
      # Since the number of players should be up to 14, we disable paging. We
      # also do not need the searching option
      options = list(paging = FALSE, searching = FALSE),
      # Allow selection of multiple rows (useful to remove more than one player
      # at once from the table.)
      selection = "multiple"
    )
  })
  # Empty the three player's input by updating their value with an empty string
  updateNumericInput(inputId = "new_player_num_away", value = "")
  updateSelectInput(inputId = "new_player_role_away", selected = "")
  updateTextInput(inputId = "new_player_name_away", value = "")
})

# When no player is listed in the away team, the table listing them is not shown
observe({
  if (is.null(input$away_players_tbl_rows_selected)) {
    shinyjs::disable("remove_player_away")
  } else {
    shinyjs::enable("remove_player_away")
  }
})

# Take care to remove from the away players table the one(s) selected when the
# remove button is hit.
observeEvent(input$remove_player_away, {
  # List the players in the table
  tbl <- players$away_team
  # Identify the players selected in the table when the remove button is hit
  to_rmv <- as.numeric(input$away_players_tbl_rows_selected)
  # Remove the selected player(s) from the table
  players$away_team <- tbl[-to_rmv, ]

  # If all players are removed (table has no row), a NULL table is rendered
  if (nrow(players$away_team) == 0) {
    output$away_players_tbl <- renderDataTable({
      NULL
    })
    # If at least one player remains in the table, it is rendered again
  } else {
    output$away_players_tbl <- renderDataTable({
      datatable(
        players$away_team,
        # Since the number of players should be up to 14, we disable paging. We
        # also do not need the searching option
        options = list(paging = FALSE, searching = FALSE),
        # Allow selection of multiple rows (useful to remove more than one player
        # at once from the table.)
        selection = "multiple"
      )
    })
  }
})

#==============================================================================|
#                           ---- All set events ----                          
#==============================================================================|

# Observer updating the list of available players for all sets and the two
# teams. The goal is that any time there is an interaction with the app, the
# observer below update the list of available players to display only the ones
# not yet selected as options for the rotation of substitutions.
observe(
  # We set priority to 1 to make sure it is executed before others and avoid
  # unwanted effects.
  priority = 1,
  {
    available_players$set_1$home <- players$home_team$Number[
      !(players$home_team$Number %in%
          c(
            get_base_rotation(input, "home", 1),
            get_substitution_players(input, "home", 1)
          ))
    ]
    available_players$set_2$home <- players$home_team$Number[
      !(players$home_team$Number %in%
          c(
            get_base_rotation(input, "home", 2),
            get_substitution_players(input, "home", 2)
          ))
    ]
    available_players$set_3$home <- players$home_team$Number[
      !(players$home_team$Number %in%
          c(
            get_base_rotation(input, "home", 3),
            get_substitution_players(input, "home", 3)
          ))
    ]
    available_players$set_4$home <- players$home_team$Number[
      !(players$home_team$Number %in%
          c(
            get_base_rotation(input, "home", 4),
            get_substitution_players(input, "home", 4)
          ))
    ]
    available_players$set_5$home <- players$home_team$Number[
      !(players$home_team$Number %in%
          c(
            get_base_rotation(input, "home", 5),
            get_substitution_players(input, "home", 5)
          ))
    ]
    available_players$set_1$away <- players$away_team$Number[
      !(players$away_team$Number %in%
          c(
            get_base_rotation(input, "away", 1),
            get_substitution_players(input, "away", 1)
          ))
    ]
    available_players$set_2$away <- players$away_team$Number[
      !(players$away_team$Number %in%
          c(
            get_base_rotation(input, "away", 2),
            get_substitution_players(input, "away", 2)
          ))
    ]
    available_players$set_3$away <- players$away_team$Number[
      !(players$away_team$Number %in%
          c(
            get_base_rotation(input, "away", 3),
            get_substitution_players(input, "away", 3)
          ))
    ]
    available_players$set_4$away <- players$away_team$Number[
      !!(players$away_team$Number %in%
           c(
             get_base_rotation(input, "away", 4),
             get_substitution_players(input, "away", 4)
           ))
    ]
    available_players$set_5$away <- players$away_team$Number[
      !!(players$away_team$Number %in%
           c(
             get_base_rotation(input, "away", 5),
             get_substitution_players(input, "away", 5)
           ))
    ]
  }
)

# Enable or disable the first score input of the first rotation in each set
# (except set 5) for the team receiving the service.
observeEvent(input$serving_set_1, {
  if (input$home_team == input$serving_set_1) {
    shinyjs::disable("set_1_r_1_p_1_away")
    shinyjs::disable("set_2_r_1_p_1_home")
    shinyjs::disable("set_3_r_1_p_1_away")
    shinyjs::disable("set_4_r_1_p_1_home")
  }
  if (input$away_team == input$serving_set_1) {
    shinyjs::disable("set_1_r_1_p_1_home")
    shinyjs::disable("set_2_r_1_p_1_away")
    shinyjs::disable("set_3_r_1_p_1_home")
    shinyjs::disable("set_4_r_1_p_1_away")
  }
})

# Enable or disable the first score input of the first rotation in set 5 for the
# team receiving the service.
observeEvent(input$serving_set_5, {
  if (input$home_team == input$serving_set_5) {
    shinyjs::disable("set_5_r_1_p_1_away")
  }
  if (input$away_team == input$serving_set_5) {
    shinyjs::disable("set_5_r_1_p_1_home")
  }
})

# Disable all the substitution player input when not all base rotation positions
# have a player assigned (and enable them when starting players are all set).
observe({
  # Loop across the five sets
  for (set in 1:5) {
    # Get the list of players assigned to the home team base rotation
    all_home_pos <- unlist(lapply(1:6, \(x) {
      input[[paste0("set_", set, "_home_p", x)]]
    }))
    # Get the list of players assigned to the away team base rotation
    all_away_pos <- unlist(lapply(1:6, \(x) {
      input[[paste0("set_", set, "_away_p", x)]]
    }))
    # If any of the home team six rotations returns an empty string, the
    # substitutions inputs are disabled.
    if (any(!nzchar(all_home_pos))) {
      lapply(1:6, \(x) {
        shinyjs::disable(paste0("set_", set, "_home_p", x, "_sub"))
      })
      # If no home team rotation returns an empty string, the substitutions
      # inputs are disabled.
    } else {
      lapply(1:6, \(x) {
        shinyjs::enable(paste0("set_", set, "_home_p", x, "_sub"))
      })
    }
    # If any of the away team six rotations returns an empty string, the
    # substitutions inputs are disabled.
    if (any(!nzchar(all_away_pos))) {
      lapply(1:6, \(x) {
        shinyjs::disable(paste0("set_", set, "_away_p", x, "_sub"))
      })
      # If no away team rotation returns an empty string, the substitutions
      # inputs are disabled.
    } else {
      lapply(1:6, \(x) {
        shinyjs::enable(paste0("set_", set, "_away_p", x, "_sub"))
      })
    }
  }
})

# For each substitution score input, we disable it as long as a player is not
# assigned to the corresponding substitution. We enable it when a player is
# assigned.
observe({
  # Loop across the five sets
  for (set in 1:5) {
    # Loop across all substitution positions
    lapply(
      1:6,
      \(x) {
        # If the home team substitution position returns an empty string, we
        # disable the corresponding substitution score inputs.
        if (!nzchar(input[[paste0("set_", set, "_home_p", x, "_sub")]])) {
          shinyjs::disable(paste0("set_", set, "_home_p", x, "_sub_1_score"))
          shinyjs::disable(paste0("set_", set, "_home_p", x, "_sub_2_score"))
          # If the home team substitution position does not return an empty
          # string, we enable the corresponding substitution score inputs.
        } else {
          shinyjs::enable(paste0("set_", set, "_home_p", x, "_sub_1_score"))
          shinyjs::enable(paste0("set_", set, "_home_p", x, "_sub_2_score"))
        }
        # If the away team substitution position returns an empty string, we
        # disable the corresponding substitution score inputs.
        if (!nzchar(input[[paste0("set_", set, "_away_p", x, "_sub")]])) {
          shinyjs::disable(paste0("set_", set, "_away_p", x, "_sub_1_score"))
          shinyjs::disable(paste0("set_", set, "_away_p", x, "_sub_2_score"))
          # If the away team substitution position does not return an empty
          # string, we enable the corresponding substitution score inputs.
        } else {
          shinyjs::enable(paste0("set_", set, "_away_p", x, "_sub_1_score"))
          shinyjs::enable(paste0("set_", set, "_away_p", x, "_sub_2_score"))
        }
      }
    )
  }
})

# Set the list of available players when "pressing" the validate button for each
# team.
observe({
  # Loop across the 5 sets
  lapply(
    1:5, \(s)
    lapply(
      # Loop across the 6 base rotations
      c(1:6),
      \(x) {
        # Create the string to access the current rotation (and the
        # corresponding substitution position) for the home team in the app
        # input.
        current_p_h <- paste0("set_", s, "_home_p", x)
        current_p_sub_h <- paste0("set_", s, "_home_p", x, "_sub")
        # Create the string to access the current rotation (and the
        # corresponding substitution position) for the away team in the app
        # input.
        current_p_a <- paste0("set_", s, "_away_p", x)
        current_p_sub_a <- paste0("set_", s, "_away_p", x, "_sub")
        
        # Update input for the current position in the rotation for the home
        # team.
        updateSelectInput(
          # Access the input selector for the current rotation position
          inputId = current_p_h,
          # Update for the choices with a vector starting with the current
          # player selected (can be empty string) and the sorted remaining
          # players.
          choices = c(
            input[[current_p_h]],
            sort(available_players[[paste0("set_", s)]]$home)
          ),
          selected = input[[current_p_h]]
        )
        # Same for the corresponding substitution position, but only if the
        # current position rotation is not empty.
        if (!is.null(input[[current_p_h]]) && nzchar(input[[current_p_h]])) {
          updateSelectInput(
            inputId = current_p_sub_h,
            choices = c(
              input[[current_p_sub_h]],
              sort(available_players[[paste0("set_", s)]]$home)
            ),
            selected = input[[current_p_sub_h]]
          )
        }
        
        # Update input for the current position in the rotation for the away
        # team.
        updateSelectInput(
          # Access the input selector for the current rotation position
          inputId = current_p_a,
          # Update for the choices with a vector starting with the current
          # player selected (can be empty string) and the sorted remaining
          # players.
          choices = c(
            input[[current_p_a]],
            sort(available_players[[paste0("set_", s)]]$away)
          ),
          selected = input[[current_p_a]]
        )
        # Same for the corresponding substitution position, but only if the
        # current position rotation is not empty.
        if (!is.null(input[[current_p_a]]) && nzchar(input[[current_p_a]])) {
          updateSelectInput(
            inputId = current_p_sub_a,
            choices = c(
              input[[current_p_sub_a]],
              sort(available_players[[paste0("set_", s)]]$away)
            ),
            selected = input[[current_p_sub_a]]
          )
        }
      }
    )
  )
})

#==============================================================================|
#                          ---- End of set events ----
#==============================================================================|

# At the end of each set, different events are checked. Based on the number of
# sets completed, it is determined if the last set played is the last one or
# not, influencing which "set tab" (or "summary tab") must be enabled next. The
# format of the scores indicating when time-outs and substitutions took place is
# also checked.

# When the away and home players are validated, the set 1 tab is made available.
# For the other sets, when the conditions are met, the "next" button is made
# available to unlock the next set.
observe({
  # By default (i.e. before the two teams' players are validated), all the set
  # tabs and the summary tab are hidden.
  if (any(!are_players_validated$home, !are_players_validated$away)) {
    shinyjs::hideElement("tab-set-1")
    shinyjs::hideElement("tab-set-2")
    shinyjs::hideElement("tab-set-3")
    shinyjs::hideElement("tab-set-4")
    shinyjs::hideElement("tab-set-5")
    # shinyjs::hideElement("tab-summary") # REMOVE
    shinyjs::disable("next_to_set_2")
    shinyjs::disable("next_to_set_3")
    shinyjs::disable("next_to_set_4")
    shinyjs::disable("next_to_set_5")
    shinyjs::disable("next_to_summary")
  } else {
    # When the two teams' players are validated, the set 1 tab is shown
    shinyjs::showElement("tab-set-1", anim = TRUE, animType = "fade")
    
    # Regarding the `next_to_set_*` and `next_to_summary` buttons below, it is
    # only when the buttons are pressed that it is determined if we have to go
    # to the next set tab or the summary tab. Be aware that the name of the
    # buttons does not mean that we go to the next set.
    # For example, at the end of set 3, the `next_to_set_4` button is enabled.
    # When clicked, a modal asking the user confirmation is displayed. If the
    # game is over (i.e. a team won 3-0), the modal displayed is the
    # `to_summary_confirm` which, when confirmed, shows the "Summary" tab and
    # skips the "Set 4" and "Set 5" tabs. If the game is not over, the modal
    # displayed is the `next_to_set_4_confirm` and, when confirmed, the "Set 4"
    # tab is shown.
    
    # When the number of sets completed (based on scores) is 1, the "next set"
    # button is enabled.
    if (n_sets() == 1) {
      shinyjs::enable("next_to_set_2")
    }
    # When the number of sets completed (based on scores) is 2, the "next set"
    # button is enabled.
    if (n_sets() == 2) {
      shinyjs::enable("next_to_set_3")
    }
    # When the number of sets completed (based on scores) is 3, the "next set"
    # button is enabled.
    if (n_sets() == 3) {
      shinyjs::enable("next_to_set_4")
    }
    # When the number of sets completed (based on scores) is 4, the "next set"
    # button is enabled.
    if (n_sets() == 4) {
      shinyjs::enable("next_to_set_5")
    }
    # When the number of sets completed (based on scores) is 5, the "next set"
    # button "summary" is enabled.
    if (n_sets() == 5) {
      shinyjs::enable("next_to_summary")
    }
  }
  
  # When after set 1 the next set button is pressed and confirmation to
  # continue is provided, the "Set 2" tab is displayed. Then the next set
  # button is disabled, as well as all the element on "Set 1" page.
  if (!is.null(input$next_to_set_2_confirm) && input$next_to_set_2_confirm) {
    shinyjs::showElement("tab-set-2", anim = TRUE, animType = "fade")
    shinyjs::disable("next_to_set_2")
  }
  # When after set 2 the next set button is pressed and confirmation to
  # continue is provided, the "Set 3" tab is displayed. Then the next set
  # button is disabled, as well as all the element on "Set 2" page.
  if (!is.null(input$next_to_set_3_confirm) && input$next_to_set_3_confirm) {
    shinyjs::showElement("tab-set-3", anim = TRUE, animType = "fade")
    shinyjs::disable("next_to_set_3")
  }
  # When after set 3 the next set button is pressed and confirmation to
  # continue is provided, whether the "Set 4" tab is displayed if the game is
  # not over yet or the "Summary" tab is displayed if the game is over. Then the
  # next set button is disabled, as well as all the element on the "Set 3" tab.
  if (!is.null(input$next_to_set_4_confirm) && input$next_to_set_4_confirm) {
    shinyjs::showElement("tab-set-4", anim = TRUE, animType = "fade")
    shinyjs::disable("next_to_set_4")
  }
  # When after set 4 the next set button is pressed and confirmation to
  # continue is provided, whether the "Set 5" tab is displayed if the game is
  # not over yet or the "Summary" tab is displayed if the game is over. Then the
  # next set button is disabled, as well as all the element on the "Set 4" tab.
  if (!is.null(input$next_to_set_5_confirm) && input$next_to_set_5_confirm) {
    shinyjs::showElement("tab-set-5", anim = TRUE, animType = "fade")
    shinyjs::disable("next_to_set_5")
  }
  # When after set 5 the next set button is pressed and confirmation to
  # continue is provided, the "Summary" tab is displayed. Then the next set
  # button is disabled, as well as all the element on the "Set 5" tab. All
  # next set buttons are also disabled as the tab can be reached from Set 3, 4,
  # and 5.
  if (!is.null(input$to_summary_confirm) && input$to_summary_confirm) {
    shinyjs::showElement("tab-summary", anim = TRUE, animType = "fade")
    shinyjs::disable("next_to_set_3")
    shinyjs::disable("next_to_set_4")
    shinyjs::disable("next_to_set_5")
    shinyjs::disable("next_to_summary")
  }
})

# The `iv_*` objects are validators used to check that the format of the
# data entered for substitutions and time-out scores is correct. It is checking
# that the scores are entered as "XX:XX" (e.g. "05:10" or "23:12").
iv_sub_set_1 <- set_validator_substitution(1)
iv_to_set_1 <- set_validator_time_out(1)
iv_sub_set_2 <- set_validator_substitution(2)
iv_to_set_2 <- set_validator_time_out(2)
iv_sub_set_3 <- set_validator_substitution(3)
iv_to_set_3 <- set_validator_time_out(3)
iv_sub_set_4 <- set_validator_substitution(4)
iv_to_set_4 <- set_validator_time_out(4)
iv_sub_set_5 <- set_validator_substitution(5)
iv_to_set_5 <- set_validator_time_out(5)

# Observer running different check when the "next set" button is clicked after
# the set 2.
observeEvent(input$next_to_set_2, {
  # Check that the scores by rotation are valid
  scores_rotations_valid <- check_scores_rotations(1, input)
  # Run the check of the format of time-outs and substitutions scores
  iv_sub_set_1$enable()
  iv_to_set_1$enable()
  # Check that a player has been assigned to each position in the base rotation
  has_base_rotation_home_6 <- are_base_rotations_complete(input, "home", 1)
  has_base_rotation_away_6 <- are_base_rotations_complete(input, "away", 1)
  
  # If all the checks ran above returned `TRUE`, the message asking
  # confirmation to switch to the next set is displayed.
  if (
    all(
      iv_sub_set_1$is_valid(),
      iv_to_set_1$is_valid(),
      !is_sub_score_missing("home", 1, input),
      !is_sub_score_missing("away", 1, input),
      has_base_rotation_home_6,
      has_base_rotation_away_6,
      scores_rotations_valid
    )
  ) {
    next_set_message(2)
  }
  # If at least one player in the home team base rotation is missing, an error
  # notification is displayed.
  if (!has_base_rotation_home_6) {
    showNotification(
      "There is at least one missing player in the home team rotation.",
      type = "error"
    )
  }
  # If at least one player in the away team base rotation is missing, an error
  # notification is displayed.
  if (!has_base_rotation_away_6) {
    showNotification(
      "There is at least one missing player in the away team rotation.",
      type = "error"
    )
  }
  # If the format of at least one substitution score for any team is incorrect,
  # an error notification is displayed.
  if (!iv_sub_set_1$is_valid()) {
    showNotification(
      "Substitution inputs have invalid format.",
      type = "error"
    )
  }
  # If the format of at least one time-out score for any team is incorrect, an
  # error notification is displayed.
  if (!iv_to_set_1$is_valid()) {
    showNotification(
      "Time-out inputs have invalid format.",
      type = "error"
    )
  }
  # If for the home team there is at least one substitution, but the score is
  # missing, an error notification is displayed.
  if (is_sub_score_missing("home", 1, input)) {
    showNotification(
      "There are substitutions for the home team without score.",
      type = "error"
    )
  }
  # If for the away team there is at least one substitution, but the score is
  # missing, an error notification is displayed.
  if (is_sub_score_missing("away", 1, input)) {
    showNotification(
      "There are substitutions for the away team without score.",
      type = "error"
    )
  }
  # If the rotation score of any team is invalid (e.g. 10-25-15), an error
  # notification is displayed.
  if (!scores_rotations_valid) {
    showNotification("Score inputs are not valid.", type = "error")
  }
})

observeEvent(input$next_to_set_3, {
  # Check that the scores by rotation are valid
  scores_rotations_valid <- check_scores_rotations(2, input)
  # Run the check of the format of time-outs and substitutions scores
  iv_sub_set_2$enable()
  iv_to_set_2$enable()
  # Check that a player has been assigned to each position in the base rotation
  has_base_rotation_home_6 <- are_base_rotations_complete(input, "home", 2)
  has_base_rotation_away_6 <- are_base_rotations_complete(input, "away", 2)
  
  # If all the checks ran above returned `TRUE`, the message asking
  # confirmation to switch to the next set is displayed.
  if (
    all(
      iv_sub_set_2$is_valid(),
      iv_to_set_2$is_valid(),
      !is_sub_score_missing("home", 2, input),
      !is_sub_score_missing("away", 2, input),
      has_base_rotation_home_6,
      has_base_rotation_away_6,
      scores_rotations_valid
    )
  ) {
    next_set_message(3)
  }
  # If at least one player in the home team base rotation is missing, an error
  # notification is displayed.
  if (!has_base_rotation_home_6) {
    showNotification(
      "There is at least one missing player in the home team rotation.",
      type = "error"
    )
  }
  # If at least one player in the away team base rotation is missing, an error
  # notification is displayed.
  if (!has_base_rotation_away_6) {
    showNotification(
      "There is at least one missing player in the away team rotation.",
      type = "error"
    )
  }
  # If the format of at least one substitution score for any team is incorrect,
  # an error notification is displayed.
  if (!iv_sub_set_2$is_valid()) {
    showNotification(
      "Substitution inputs have invalid format.",
      type = "error"
    )
  }
  # If the format of at least one time-out score for any team is incorrect, an
  # error notification is displayed.
  if (!iv_to_set_2$is_valid()) {
    showNotification(
      "Time-out inputs have invalid format.",
      type = "error"
    )
  }
  # If for the home team there is at least one substitution, but the score is
  # missing, an error notification is displayed.
  if (is_sub_score_missing("home", 2, input)) {
    showNotification(
      "There are substitutions for the home team without score.",
      type = "error"
    )
  }
  # If for the away team there is at least one substitution, but the score is
  # missing, an error notification is displayed.
  if (is_sub_score_missing("away", 2, input)) {
    showNotification(
      "There are substitutions for the away team without score.",
      type = "error"
    )
  }
  # If the rotation score of any team is invalid (e.g. 10-25-15), an error
  # notification is displayed.
  if (!scores_rotations_valid) {
    showNotification("Score inputs are not valid.", type = "error")
  }
})

observeEvent(input$next_to_set_4, {
  # Check that the scores by rotation are valid
  scores_rotations_valid <- check_scores_rotations(3, input)
  # Run the check of the format of time-outs and substitutions scores
  iv_sub_set_3$enable()
  iv_to_set_3$enable()
  # Check that a player has been assigned to each position in the base rotation
  has_base_rotation_home_6 <- are_base_rotations_complete(input, "home", 3)
  has_base_rotation_away_6 <- are_base_rotations_complete(input, "away", 3)
  
  # If all the checks ran above returned `TRUE`, the message asking
  # confirmation to switch to the next set is displayed.
  if (
    all(
      iv_sub_set_3$is_valid(),
      iv_to_set_3$is_valid(),
      !is_sub_score_missing("home", 3, input),
      !is_sub_score_missing("away", 3, input),
      has_base_rotation_home_6,
      has_base_rotation_away_6,
      scores_rotations_valid
    )
  ) {
    if (!is_game_over()) {
      next_set_message(4)
    } else {
      data_ready_for_export(TRUE)
      next_set_message("summary")
    }
  }
  # If at least one player in the home team base rotation is missing, an error
  # notification is displayed.
  if (!has_base_rotation_home_6) {
    showNotification(
      "There is at least one missing player in the home team rotation.",
      type = "error"
    )
  }
  # If at least one player in the away team base rotation is missing, an error
  # notification is displayed.
  if (!has_base_rotation_away_6) {
    showNotification(
      "There is at least one missing player in the away team rotation.",
      type = "error"
    )
  }
  # If the format of at least one substitution score for any team is incorrect,
  # an error notification is displayed.
  if (!iv_sub_set_3$is_valid()) {
    showNotification(
      "Substitution inputs have invalid format.",
      type = "error"
    )
  }
  # If the format of at least one time-out score for any team is incorrect, an
  # error notification is displayed.
  if (!iv_to_set_3$is_valid()) {
    showNotification(
      "Time-out inputs have invalid format.",
      type = "error"
    )
  }
  # If for the home team there is at least one substitution, but the score is
  # missing, an error notification is displayed.
  if (is_sub_score_missing("home", 3, input)) {
    showNotification(
      "There are substitutions for the home team without score.",
      type = "error"
    )
  }
  # If for the away team there is at least one substitution, but the score is
  # missing, an error notification is displayed.
  if (is_sub_score_missing("away", 3, input)) {
    showNotification(
      "There are substitutions for the away team without score.",
      type = "error"
    )
  }
  # If the rotation score of any team is invalid (e.g. 10-25-15), an error
  # notification is displayed.
  if (!scores_rotations_valid) {
    showNotification("Score inputs are not valid.", type = "error")
  }
})

observeEvent(input$next_to_set_5, {
  # Check that the scores by rotation are valid
  scores_rotations_valid <- check_scores_rotations(4, input)
  # Run the check of the format of time-outs and substitutions scores
  iv_sub_set_4$enable()
  iv_to_set_4$enable()
  # Check that a player has been assigned to each position in the base rotation
  has_base_rotation_home_6 <- are_base_rotations_complete(input, "home", 4)
  has_base_rotation_away_6 <- are_base_rotations_complete(input, "away", 4)
  
  # If all the checks ran above returned `TRUE`, the message asking
  # confirmation to switch to the next set is displayed.
  if (
    all(
      iv_sub_set_4$is_valid(),
      iv_to_set_4$is_valid(),
      !is_sub_score_missing("home", 4, input),
      !is_sub_score_missing("away", 4, input),
      has_base_rotation_home_6,
      has_base_rotation_away_6,
      scores_rotations_valid
    )
  ) {
    if (!is_game_over()) {
      next_set_message(5, input)
    } else {
      # Use `set = NULL` to indicate this was the last set
      next_set_message(set = NULL)
      data_ready_for_export(TRUE)
    }
  }
  # If at least one player in the home team base rotation is missing, an error
  # notification is displayed.
  if (!has_base_rotation_home_6) {
    showNotification(
      "There is at least one missing player in the home team rotation.",
      type = "error"
    )
  }
  # If at least one player in the away team base rotation is missing, an error
  # notification is displayed.
  if (!has_base_rotation_away_6) {
    showNotification(
      "There is at least one missing player in the away team rotation.",
      type = "error"
    )
  }
  # If the format of at least one substitution score for any team is incorrect,
  # an error notification is displayed.
  if (!iv_sub_set_4$is_valid()) {
    showNotification(
      "Substitution inputs have invalid format.",
      type = "error"
    )
  }
  # If the format of at least one time-out score for any team is incorrect, an
  # error notification is displayed.
  if (!iv_to_set_4$is_valid()) {
    showNotification(
      "Time-out inputs have invalid format.",
      type = "error"
    )
  }
  # If for the home team there is at least one substitution, but the score is
  # missing, an error notification is displayed.
  if (is_sub_score_missing("home", 4, input)) {
    showNotification(
      "There are substitutions for the home team without score.",
      type = "error"
    )
  }
  # If for the away team there is at least one substitution, but the score is
  # missing, an error notification is displayed.
  if (is_sub_score_missing("away", 4, input)) {
    showNotification(
      "There are substitutions for the away team without score.",
      type = "error"
    )
  }
  # If the rotation score of any team is invalid (e.g. 10-25-15), an error
  # notification is displayed.
  if (!scores_rotations_valid) {
    showNotification("Score inputs are not valid.", type = "error")
  }
})

observeEvent(input$next_to_summary, {
  # Check that the scores by rotation are valid
  scores_rotations_valid <- check_scores_rotations(5, input)
  # Run the check of the format of time-outs and substitutions scores
  iv_sub_set_5$enable()
  iv_to_set_5$enable()
  # Check that a player has been assigned to each position in the base rotation
  has_base_rotation_home_6 <- are_base_rotations_complete(input, "home", 5)
  has_base_rotation_away_6 <- are_base_rotations_complete(input, "away", 5)
  
  # If all the checks ran above returned `TRUE`, the message asking
  # confirmation to switch to the next set is displayed.
  if (
    all(
      iv_sub_set_5$is_valid(),
      iv_to_set_5$is_valid(),
      !is_sub_score_missing("home", 5, input),
      !is_sub_score_missing("away", 5, input),
      has_base_rotation_home_6,
      has_base_rotation_away_6,
      scores_rotations_valid
    )
  ) {
    next_set_message("summary")
  }
  # If at least one player in the home team base rotation is missing, an error
  # notification is displayed.
  if (!has_base_rotation_home_6) {
    showNotification(
      "There is at least one missing player in the home team rotation.",
      type = "error"
    )
  }
  # If at least one player in the away team base rotation is missing, an error
  # notification is displayed.
  if (!has_base_rotation_away_6) {
    showNotification(
      "There is at least one missing player in the away team rotation.",
      type = "error"
    )
  }
  # If the format of at least one substitution score for any team is incorrect,
  # an error notification is displayed.
  if (!iv_sub_set_5$is_valid()) {
    showNotification(
      "Substitution inputs have invalid format.",
      type = "error"
    )
  }
  # If the format of at least one time-out score for any team is incorrect, an
  # error notification is displayed.
  if (!iv_to_set_5$is_valid()) {
    showNotification(
      "Time-out inputs have invalid format.",
      type = "error"
    )
  }
  # If for the home team there is at least one substitution, but the score is
  # missing, an error notification is displayed.
  if (is_sub_score_missing("home", 5, input)) {
    showNotification(
      "There are substitutions for the home team without score.",
      type = "error"
    )
  }
  # If for the away team there is at least one substitution, but the score is
  # missing, an error notification is displayed.
  if (is_sub_score_missing("away", 5, input)) {
    showNotification(
      "There are substitutions for the away team without score.",
      type = "error"
    )
  }
  # If the rotation score of any team is invalid (e.g. 10-25-15), an error
  # notification is displayed.
  if (!scores_rotations_valid) {
    showNotification("Score inputs are not valid.", type = "error")
  }
})

# When the confirmation button to switch to the next set is pressed, the modal
# asking for confirmation is removed.
observeEvent(input$next_to_set_2_confirm, {
  removeModal()
})
observeEvent(input$next_to_set_3_confirm, {
  removeModal()
})
observeEvent(input$next_to_set_4_confirm, {
  removeModal()
})
observeEvent(input$next_to_set_5_confirm, {
  removeModal()
})
observeEvent(input$to_summary_confirm, {
  removeModal()
})


#==============================================================================|
#                         ---- "Summary" tab events ----                        
#==============================================================================|

# Observer extracting, when a set is over (based on scores only), the score,
# the number of substitutions, the number of time-outs for team in each set.
# Then, it renders the different text element displayed in the summary tab.
observe({
  # Extract the score for each team and each set
  home_score_sets <- get_set_scores("home", input)
  away_score_sets <- get_set_scores("away", input)
  # Check that the scores for each set are valid
  scores <- validate_set_scores(home_score_sets, away_score_sets)
  # Get the number of substitutions and time-outs
  substitutions <- get_n_substitutions(input)
  time_outs <- get_n_time_out(input)
  # Determine if the game is over (i.e. when a team has win 3 sets)
  is_game_over(attr(scores, "is_over"))
  # Get the number of sets played
  n_sets(attr(scores, "n_sets"))
  
  # When the scores are valid, the scores, number of substitutions, and number
  # of time-outs for sets 1 to 3 are rendered in the summary tab.
  if (attr(scores, "is_valid")) {
    output$home_score_set_1 <- renderText({ scores$home[1] })
    output$home_score_set_2 <- renderText({ scores$home[2] })
    output$home_score_set_3 <- renderText({ scores$home[3] })
    
    output$away_score_set_1 <- renderText({ scores$away[1] })
    output$away_score_set_2 <- renderText({ scores$away[2] })
    output$away_score_set_3 <- renderText({ scores$away[3] })
    
    output$home_sub_set_1 <- renderText({ substitutions$home[1] })
    output$home_sub_set_2 <- renderText({ substitutions$home[2] })
    output$home_sub_set_3 <- renderText({ substitutions$home[3] })
    
    output$away_sub_set_1 <- renderText({ substitutions$away[1] })
    output$away_sub_set_2 <- renderText({ substitutions$away[2] })
    output$away_sub_set_3 <- renderText({ substitutions$away[3] })
    
    output$home_to_set_1 <- renderText({ time_outs$home[1] })
    output$home_to_set_2 <- renderText({ time_outs$home[2] })
    output$home_to_set_3 <- renderText({ time_outs$home[3] })
    
    output$away_to_set_1 <- renderText({ time_outs$away[1] })
    output$away_to_set_2 <- renderText({ time_outs$away[2] })
    output$away_to_set_3 <- renderText({ time_outs$away[3] })
    
    # If the number of sets if higher than 3, the scores, number of
    # substitutions, and number of time-outs for set 4 are rendered in the
    # summary tab.
    if (n_sets() > 3) {
      output$home_score_set_4 <- renderText({ scores$home[4] })
      output$away_score_set_4 <- renderText({ scores$away[4] })
      
      output$home_sub_set_4 <- renderText({ substitutions$home[4] })
      output$away_sub_set_4 <- renderText({ substitutions$away[4] })
      
      output$home_to_set_4 <- renderText({ time_outs$home[4] })
      output$away_to_set_4 <- renderText({ time_outs$away[4] })
    }
    # If the number of sets if higher than 4, the scores, number of
    # substitutions, and number of time-outs for set 4 are rendered in the
    # summary tab.
    if (n_sets() > 4) {
      output$home_score_set_5 <- renderText({ scores$home[5] })
      output$away_score_set_5 <- renderText({ scores$away[5] })
      
      output$home_sub_set_5 <- renderText({ substitutions$home[5] })
      output$away_sub_set_5 <- renderText({ substitutions$away[5] })
      
      output$home_to_set_5 <- renderText({ time_outs$home[5] })
      output$away_to_set_5 <- renderText({ time_outs$away[5] })
    }
    # Render the number of sets won by the teams in the summary tab
    output$away_sets <- renderText({
      sum(scores$away > scores$home, na.rm = TRUE)
    })
    output$home_sets <- renderText({
      sum(scores$home > scores$away, na.rm = TRUE)
    })
    
    # In case the scores are not valid, all the element on the summary tab are
    # rendered as empty strings.
  } else {
    
    output$home_score_set_1 <- renderText({ "" })
    output$home_score_set_2 <- renderText({ "" })
    output$home_score_set_3 <- renderText({ "" })
    output$home_score_set_4 <- renderText({ "" })
    output$home_score_set_5 <- renderText({ "" })
    
    output$away_score_set_1 <- renderText({ "" })
    output$away_score_set_2 <- renderText({ "" })
    output$away_score_set_3 <- renderText({ "" })
    output$away_score_set_4 <- renderText({ "" })
    output$away_score_set_5 <- renderText({ "" })
    
    output$home_sub_set_1 <- renderText({ "" })
    output$home_sub_set_2 <- renderText({ "" })
    output$home_sub_set_3 <- renderText({ "" })
    output$home_sub_set_4 <- renderText({ "" })
    output$home_sub_set_5 <- renderText({ "" })
    
    output$away_sub_set_1 <- renderText({ "" })
    output$away_sub_set_2 <- renderText({ "" })
    output$away_sub_set_3 <- renderText({ "" })
    output$away_sub_set_4 <- renderText({ "" })
    output$away_sub_set_5 <- renderText({ "" })
    
    output$home_to_set_1 <- renderText({ "" })
    output$home_to_set_2 <- renderText({ "" })
    output$home_to_set_3 <- renderText({ "" })
    output$home_to_set_4 <- renderText({ "" })
    output$home_to_set_5 <- renderText({ "" })
    
    output$away_to_set_1 <- renderText({ "" })
    output$away_to_set_2 <- renderText({ "" })
    output$away_to_set_3 <- renderText({ "" })
    output$away_to_set_4 <- renderText({ "" })
    output$away_to_set_5 <- renderText({ "" })
    
    output$away_sets <- renderText({ "" })
    output$home_sets <- renderText({ "" })
  }
  
  output$home_team_out <- renderText({ input$home_team })
  output$away_team_out <- renderText({ input$away_team })
})

# Observer preparing the data for export when their is a confirmation to go to
# the summary tab.
observeEvent(input$to_summary_confirm, {
  # When the data are ready for export (i.e. when the next set button is hit
  # and the game is over), we start the process of preparing the data for
  # export.
  if (data_ready_for_export()) {
    # Create a list that will index the wrangled data for each set
    export_dat_list <- list()
    
    # We loop over each set using the number of sets played stored in the
    # reactive `n_sets()`.
    for (i in 1:n_sets()) {
      # We get from the app input the score by rotation for each team and assign
      # each score vector to a named list.
      set_scores <- get_rotation_scores_input(i, input)
      scores <- list(
        home = set_scores$home,
        away = set_scores$away
      )
      # We set the "serving" attribute with the team (home or away) that started
      # to serve during the set.
      attr(scores, "serving") <- get_set_serving_team(input, i)
      
      # We extract from the app input the scores when time-outs where requested
      # for each team separately (always starting with the requesting team.)
      time_outs <- list(
        home = get_time_out_scores(input, "home", i),
        away = get_time_out_scores(input, "away", i)
      )
      # We set the "home" and "away" attributes to the `time_outs` object so
      # we can retrieve the name of home and away teams.
      attr(time_outs$home, "team") <- input$home_team
      attr(time_outs$away, "team") <- input$away_team
      
      # We get from the app input all necessary information regarding
      # substitutions. For each team, we get the rotation at the beginning of
      # the set, the substitution rotation (NA when there was no substitution
      # for the corresponding position, and a player number which did not
      # started the set instead).
      substitutions <- list(
        home = list(
          rotation = get_base_rotation(input, "home", i),
          sub = get_substitution_players(input, "home", i),
          score_in = get_substitution_scores(input, "home", i, "in"),
          score_out = get_substitution_scores(input, "home", i, "out")
        ),
        away = list(
          rotation = get_base_rotation(input, "away", i),
          sub = get_substitution_players(input, "away", i),
          score_in = get_substitution_scores(input, "away", i, "in"),
          score_out = get_substitution_scores(input, "away", i, "out")
        )
      )
      
      # We set the "home" and "away" attributes to the `substitutions` object so
      # we can retrieve the name of home and away teams.
      attr(substitutions$home, "team") <- input$home_team
      attr(substitutions$away, "team") <- input$away_team
      
      # We prepare the data export for the current set
      export_dat_list[[i]] <- wrangle_set_data(
        i,
        scores,
        time_outs,
        substitutions
      )
    }
    
    # We bind together the wrangled data for each set
    export_dat_list <- list_rbind(export_dat_list)
    
    # We make available for download the wrangled data
    output$export_game_data <- downloadHandler(
      filename = function() {
        paste0("vbdata-", Sys.Date(), ".csv")
      },
      content = function(file) {
        write.csv2(export_dat_list, file)
      }
    )
  }
})

observeEvent(input$close_app, {
  showModal(
    modalDialog(
      title = "Are you sure you want to close the app?",
      # Some instructions on how to use the import tab
      list(
        "The app does not save any data. Closing the app will thus cause ",
        "losing all the data imported. Make sure you downloaded the game data ",
        "before closing the app. After closing the app, simply close your",
        "browser window."
      ),
      footer = tagList(
        modalButton("Cancel"),
        actionButton(
          "close_app_confirm",
          "Confirm closing app"
        )
      ),
      easyClose = FALSE,
      size = "m"
    )
  )
})

observeEvent(input$close_app_confirm, {
  session$Close()
})

```
